-- Check if duplicate rows exist in PROF_BILLING_DETAIL

SELECT 
BILL_DETAIL_ID,
COUNT(*) as num_instances,
max(BILL_ID) as BILL_ID,
max(BILL_SELECTION_DATE) as BILL_SELECTION_DATE,
max(LINE_NUMBER) as LINE_NUMBER,
max(TOTAL_AMOUNT_PAID_PER_LINE) as TOTAL_AMOUNT_PAID_PER_LINE,
max(TOTAL_CHARGE_PER_LINE) as TOTAL_CHARGE_PER_LINE,
max(DAYS_UNITS_BILLED) as DAYS_UNITS_BILLED,
max(DAYS_UNITS_PAID) as DAYS_UNITS_PAID,
max(DAYS_UNITS_CODE) as DAYS_UNITS_CODE,
max(SERVICE_LINE_FROM_DATE) as SERVICE_LINE_FROM_DATE,
max(SERVICE_LINE_TO_DATE) as SERVICE_LINE_TO_DATE,
max(TREATMENT_LINE_AUTHORIZATION) as TREATMENT_LINE_AUTHORIZATION_NUMBER,
max(HCPCS_LINE_PROCEDURE_BILLED) as HCPCS_LINE_PROCEDURE_BILLED,
max(HCPCS_LINE_PROCEDURE_PAID) as HCPCS_LINE_PROCEDURE_PAID,
max(PROCEDURE_DESCRIPTION) as PROCEDURE_DESCRIPTION
from {{ source('texas_claims_src', 'PROF_BILLING_DETAIL') }}
GROUP BY BILL_DETAIL_ID
HAVING COUNT(*) > 1
