version: 2

sources:
 - name: texas_claims_src
   database: "FIVETRAN_DATABASE" 
   schema: "TEXAS_CLAIMS_BILLING_GD" 
   tables:
    - name: INST_BILLING_HEADER
    - name: INST_BILLING_DETAIL
    - name: PROF_BILLING_HEADER
    - name: PROF_BILLING_DETAIL

models:
  - name: stg_inst_billing_header
    description: ""
    columns:
      - name: bill_id
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: bill_selection_date
        data_type: date

      - name: bill_type
        data_type: varchar

      - name: insurer_fein
        data_type: varchar

      - name: insurer_postal_code
        data_type: varchar

      - name: date_insurer_received_bill
        data_type: date

      - name: date_insurer_paid_bill
        data_type: date

      - name: facility_fein
        data_type: varchar

      - name: facility_name
        data_type: varchar

      - name: facility_address
        data_type: varchar

      - name: facility_city
        data_type: varchar

      - name: facility_state_code
        data_type: varchar

      - name: facility_postal_code
        data_type: varchar

      - name: facility_country_code
        data_type: varchar

      - name: facility_code
        data_type: varchar

      - name: employer_fein
        data_type: varchar

      - name: employer_physical_city
        data_type: varchar

      - name: employer_physical_state_code
        data_type: varchar

      - name: employer_physical_postal
        data_type: varchar

      - name: billing_provider_fein
        data_type: varchar

      - name: rendering_bill_provider_fein
        data_type: varchar

      - name: rendering_bill_provider_first_name
        data_type: varchar

      - name: referring_provider_first_name
        data_type: varchar

      - name: billing_provider_last_name
        data_type: varchar

      - name: rendering_bill_provider_last_name
        data_type: varchar

      - name: referring_provider_last_name
        data_type: varchar

      - name: billing_provider_address
        data_type: varchar

      - name: rendering_bill_provider_address
        data_type: varchar

      - name: billing_provider_city
        data_type: varchar

      - name: rendering_bill_provider_city
        data_type: varchar

      - name: billing_provider_state_code
        data_type: varchar

      - name: rendering_bill_provider_state
        data_type: varchar

      - name: billing_provider_postal_code
        data_type: varchar

      - name: rendering_bill_provider_postal
        data_type: varchar

      - name: billing_provider_country
        data_type: varchar

      - name: rendering_bill_provider_country_code
        data_type: varchar

      - name: admission_hour
        data_type: time

      - name: admission_date
        data_type: date

      - name: admission_type_code
        data_type: varchar

      - name: admitting_diagnosis_code
        data_type: varchar

      - name: principal_diagnosis_code
        data_type: varchar

      - name: employee_mailing_city
        data_type: varchar

      - name: employee_mailing_state_code
        data_type: varchar

      - name: employee_mailing_postal_code
        data_type: varchar

      - name: employee_mailing_country
        data_type: varchar

      - name: employee_date_of_birth
        data_type: date

      - name: employee_gender_code
        data_type: varchar

      - name: employee_marital_status_code
        data_type: varchar

      - name: employee_date_of_injury
        data_type: date

      - name: transformed_timestamp
        data_type: timestamp_ltz

  - name: stg_inst_billing_detail
    description: ""
    columns:
      - name: bill_detail_id
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: bill_id
        data_type: varchar
        tests:
          - not_null

      - name: bill_selection_date
        data_type: date

      - name: line_number
        data_type: varchar

      - name: total_amount_paid_per_line
        data_type: number

      - name: total_charge_per_line
        data_type: number

      - name: days_units_billed
        data_type: number

      - name: days_units_paid
        data_type: number

      - name: days_units_code
        data_type: varchar

      - name: service_line_from_date
        data_type: date

      - name: service_line_to_date
        data_type: date

      - name: treatment_line_authorization_number
        data_type: varchar

      - name: hcpcs_line_procedure_billed
        data_type: varchar

      - name: hcpcs_line_procedure_paid
        data_type: varchar

      - name: procedure_description
        data_type: varchar

      - name: transformed_timestamp
        data_type: timestamp_ltz

  - name: stg_prof_billing_header
    description: ""
    columns:
      - name: bill_id
        data_type: varchar
        tests:
          - not_null
          - unique
          
      - name: bill_selection_date
        data_type: date

      - name: bill_type
        data_type: varchar

      - name: insurer_fein
        data_type: varchar

      - name: insurer_postal_code
        data_type: varchar

      - name: date_insurer_received_bill
        data_type: date

      - name: date_insurer_paid_bill
        data_type: date

      - name: facility_fein
        data_type: varchar

      - name: facility_name
        data_type: varchar

      - name: facility_address
        data_type: varchar

      - name: facility_city
        data_type: varchar

      - name: facility_state_code
        data_type: varchar

      - name: facility_postal_code
        data_type: varchar

      - name: facility_country_code
        data_type: varchar

      - name: employer_fein
        data_type: varchar

      - name: employer_physical_city
        data_type: varchar

      - name: employer_physical_state_code
        data_type: varchar

      - name: employer_physical_postal
        data_type: varchar

      - name: billing_provider_fein
        data_type: varchar

      - name: rendering_bill_provider_fein
        data_type: varchar

      - name: referring_provider_fein
        data_type: varchar

      - name: billing_provider_first_name
        data_type: varchar

      - name: rendering_bill_provider_first_name
        data_type: varchar

      - name: referring_provider_first_name
        data_type: varchar

      - name: billing_provider_last_name
        data_type: varchar

      - name: rendering_bill_provider_last_name
        data_type: varchar

      - name: referring_provider_last_name
        data_type: varchar

      - name: billing_provider_address
        data_type: varchar

      - name: rendering_bill_provider_address
        data_type: varchar

      - name: billing_provider_city
        data_type: varchar

      - name: rendering_bill_provider_city
        data_type: varchar

      - name: billing_provider_state_code
        data_type: varchar

      - name: rendering_bill_provider_state
        data_type: varchar

      - name: billing_provider_postal_code
        data_type: varchar

      - name: rendering_bill_provider_postal
        data_type: varchar

      - name: billing_provider_country
        data_type: varchar

      - name: rendering_bill_provider_country_code
        data_type: varchar

      - name: employee_mailing_city
        data_type: varchar

      - name: employee_mailing_state_code
        data_type: varchar

      - name: employee_mailing_postal_code
        data_type: varchar

      - name: employee_mailing_country
        data_type: varchar

      - name: employee_date_of_birth
        data_type: date

      - name: employee_gender_code
        data_type: varchar

      - name: employee_marital_status_code
        data_type: varchar

      - name: employee_date_of_injury
        data_type: date

      - name: transformed_timestamp
        data_type: timestamp_ltz
  - name: stg_prof_billing_detail
    description: ""
    columns:
      - name: bill_detail_id
        data_type: varchar
        tests:
          - not_null
          - unique

      - name: bill_id
        data_type: varchar

      - name: bill_selection_date
        data_type: date

      - name: line_number
        data_type: varchar

      - name: total_amount_paid_per_line
        data_type: number

      - name: total_charge_per_line
        data_type: number

      - name: days_units_billed
        data_type: number

      - name: days_units_paid
        data_type: number

      - name: days_units_code
        data_type: varchar

      - name: service_line_from_date
        data_type: date

      - name: service_line_to_date
        data_type: date

      - name: treatment_line_authorization_number
        data_type: varchar

      - name: hcpcs_line_procedure_billed
        data_type: varchar

      - name: hcpcs_line_procedure_paid
        data_type: varchar

      - name: procedure_description
        data_type: varchar

      - name: transformed_timestamp
        data_type: timestamp_ltz
